services:
  - type: web
    name: evolution-api
    runtime: docker
    plan: free
    envVars:
      - key: AUTHENTICATION_TYPE
        value: apikey
      - key: AUTHENTICATION_API_KEY
        value: evolution-api
      - key: AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES
        value: "true"
      - key: DEL_INSTANCE
        value: "false"
      - key: SERVER_URL
        value: https://evolution-api-v2-1-1-5yjk.onrender.com
